                                                                                                                                                                                                      #include   \
                                                                                                                                                                                                      <stdio.h>//
                                                                                                                                                                                                      #include   \
                                                                                                                                                                                                      <stdlib.h>//
                                                                                                                                                                                                      #include   \
                                                                                                                                                                                                      <time.h>/**/
                                                                                                                                                                                                      #ifdef/*a*/\
                                                                                                                                                                                                      _WIN32/*d_*/
                                                                                                                                                                                                      #include   \
                                                                                                                                                                                                      <conio.h>//
                #include<windows.h>/*f*/                                              /*ds); tv.tv_s*/                                          /*ec = timeout_ms / */                                /*1000; tv*/                                                                      /*.tv_usec = (ti*/                                                                                                                      /*meout_ms % 1000)*/
            int getch_timeout(int timeout_ms                      ){clock_t         start_time=clock();                                 while(clock()-start_time</* * 10*/                            timeout_ms){                        if(_kbhit())/**/                          return _getch();Sleep(1);}                                                                                                              return-1;}/*00; int ret = se*/
        #else/*lect(STDIN_FILENO + 1, &rea*/                      /*d_fds,*/      /* NULL, NULL, &tv); if */                          /*(ret > 0) ch = getchar(); else ch = */                        /*-1; tcse*/                      /*tattr(STDIN_*/                        /*FILENO, TCSANOW, &old); retu*/                                                                                                        /*rn ch;}#endif#define ROWS 24#d*/
      #include<termios.h>/*efine COLS 32en*/                      /*um Pix*/    /*elType {NONE, BODY, FOOD};*/                        /*int screen[ROWS][COLS];struct Pos{ int*/                      /* x; int */                    /*y;};struct P*/                        /*os head_pos;struct Pos food_pos;in*/                                                                                                  /*t score = 0;int pos_equal(struct*/
    #include<unistd.h>/* Pos pos1, struct */                      /*Pos po*/  /*s2){ return pos1.x == pos2.x &*/                      /*& pos1.y == pos2.y;}struct BodyElement*/                      /*{ struct*/                  /* Pos pos; st*/                        /*ruct BodyEleme*/  /*nt *next;};struc*/                                                                                                /*t BodyElement *body_tail;struct Bo*/
  #include/*dyEl*/                    /*em*/                      <sys/select.h>/*en*/            /*t *body_he*/                      /*ad;voi*/                  /*d body_appen*/                    /*d(struct*/                /* Pos pos){ s*/                        /*truct BodyEl*/            /*ement *new =*/                                                                                            /* malloc(sizeof*/              /*(str*/
  int/*uct Bod*/                                                  getch_timeout(int                 timeout_ms){                      /**/                          struct termios                    old,new;/**/              fd_set read_fds;                          struct/*yE*/                    timeval tv;int                                                                                        ch;tcgetattr(                           //
  STDIN_FILENO                                                    ,&old);new=old;new                .c_lflag&=~(                                                      ICANON|ECHO);                   new.c_cc[               VMIN]=0;new.c_cc                          [VTIME]=0;/**/                      tcsetattr(                                                                                          STDIN_FILENO,
  TCSANOW,&new                                                    );FD_ZERO(&/*l*/                    read_fds);                                                      FD_SET(/*eme*/                  STDIN_FILENO          ,&read_fds);tv.                             tv_sec=/*n*/                        timeout_ms/                                                                                       1000;tv./*t)*/
  tv_usec=(                                                       timeout_ms%                         1000)*1000;                                                       int ret=/**/                  select(/*)*/          STDIN_FILENO+1                            ,&read_fds,                           NULL,NULL,&tv)                                                                                    ;if(ret>0)ch=
  getchar();                                                      else ch=-1;                         tcsetattr(                                                        STDIN_FILENO                  ,TCSANOW,&          old);return ch                              ;}/*; if (*/                            /*!new) ex*/                                                                                  /*it(1); new*/
  #endif/*->po*/                                                  /*s = pos;*/                        /* new->ne*/                                                      /*xt = NUL*/                  /*L; if (b*/      /*ody_head) */                                /*{ body_t*/                            /*ail->nex*/                                                                                  /*t = new; b*/
  #define ROWS 24                                                 /*ody_tail*/                        /* = new; */                                                      /*} else b*/                  /*ody_tail*/    /* = body_he*/                                  /*ad = new*/                            /*;}void b*/                                                                                  /*ody_popt*/
    #define COLS 32/*a*/                                          /*il(void)*/                        /*{ if (!b*/                                                      /*ody_head*/                  /*) return*/  /*; struct B*/                                  /*odyElement*/                            /* *tmp = */                                                                                  /*body_hea*/
      enum PixelType{NONE,BODY                                    ,FOOD};int                          screen[ROWS]                              [COLS];struct Pos{int x;int y;};/**/                  struct Pos head_pos;struct                                    Pos food_pos;int score=0;int pos_equal(struct Pos pos1                                                                                  ,struct Pos
        pos2){return pos1.x==pos2.x                               &&pos1.y==                          pos2.y;}/**/                          struct BodyElement{struct Pos pos;struct                  BodyElement*next;};/*d*/                                      struct BodyElement*body_tail;struct BodyElement*/*; */                                                                                body_head;void
          body_append(struct Pos pos){                            struct/*bo*/                        BodyElement*                      new=malloc(sizeof(struct BodyElement));if(!                   new)exit(1);new->pos=pos;                                     new->next=NULL;if(body_head){body_tail->next=new;/*d*/                                                                                body_tail=new;
              }else body_tail=body_head=                          new;}void                           body_poptail                    (void){if(!body_head)return;struct BodyElement                  *tmp=/*y_h*/  body_head;/**/                                  body_head=body_head->next;if(!body_head)body_tail=NULL                                                                                ;free(tmp);}//
                    void print_screen(void){                      printf("Sco"                        "re: %d\n",                   score);putchar('+');                for(int i=0;                  i<COLS*2;i++    )putchar('-');                                puts("+");for(                                                                                                                        int i=0;i<ROWS
                        ;i++){putchar('|');for                    (int j=0;j<                         COLS;j++){                    switch(screen[                      i][j]){case                   NONE:fputs(       "  ",stdout);                               break;case/**/                                                                                                                          BODY:fputs(
                            "##",stdout);break                    ;case FOOD:                         fputs("@@",                 stdout);break;                        }}puts("|");                  }putchar('+'        );for(int i=                              0;i<COLS*2;i++                                                                                                                          )putchar('-'
                                );puts("+");}                     void/*ead */                        clear_screen                (void){for(int                        i=0;i<ROWS;i                  ++)for(int j          =0;j<COLS;j                               ++)screen[i]                                                                                                                          [j]=NONE;}//
                                  void gameover(                  void){printf                        ("\33[2J");                 printf("Gam"                          "e over. Yo"                  "ur score: "          "%d\n",score);                            exit(0);}                                                                                                                             void/*= body*/
                                  random_food(                    void){/*_h*/                        food_pos.x=                 rand()%COLS;                          food_pos.y=                   rand()%ROWS;          for(struct/*ea*/                          BodyElement*                                                                          part=/*d*/                                      body_head;part
                                  ;part=part->                    next)if(/**/                        pos_equal(                  part->pos,                          food_pos))/**/                  return/*->*/            random_food();                          screen[/*nex*/                                                                      food_pos.y][                                        food_pos.x]=//
                                  FOOD;}int main                  (void){srand                        ((unsigned)                 time(NULL));                    clear_screen();int                  ch="wasd"[                rand()%4];/*t;*/                        head_pos.x=                                                                     rand()%COLS;/* i*/                                    head_pos.y=rand(
                                  )%ROWS;/*f*/                    body_append(                        head_pos);                  random_food();                int pause=0;for(;;){                  int c=/* (*/                getch_timeout(                        100);if(c=='\33'                                                                )gameover();if(c==                                      'p')pause=!pause                        ;
if(pause)                     continue;if(c==                     'w'||c=='s'                         ||c=='a'||c                 =='d')ch=c;/*!*/          screen[head_pos.y][/*b*/                  head_pos.x]=                  NONE;switch(ch){                      case'w':head_pos.y                      --;                                   break;case's':/*od*/                                    head_pos.y++;break;               case'a':
head_pos.x--;break;case'd':head_pos.x++;/**/                      break;/*y_*/                        default:/**/                  break;}if(head_pos.x<0||head_pos.y<0||head_pos.x                  >=COLS||/**/                    head_pos.y>=ROWS                      )gameover();screen[head_pos.y][head_pos.x]=                                 BODY;for(struct/*h*/                                      BodyElement*part=body_head;part;part=//
part->next){struct Pos pos=part->pos;                             screen[pos.y                        ][pos.x]=                       BODY;if(pos_equal(pos,head_pos    ))gameover()                  ;}/*ead) b*/                        body_append(/**/                      head_pos);if(pos_equal(head_pos,food_pos                                )){random_food();                                             score++;}else{struct Pos pos=/*ody*/
body_head->pos;if(body_head){screen[                              pos.y][pos.x                        ]=NONE;/*_*/                      body_poptail();}}/*tail */      print_screen                  ();printf(""                        "\33[%dA\33[%dD",                       ROWS+3,COLS+2);}return 0;}/*= NULL; */                                  /*free(tmp);*/                                                  /*}void print_screen(void){ pr*/
      /*intf("Score: %d\n", sc*/                                                                                                            /*ore); putchar(*/                                                                                                                          /*'+'); for (int i = 0; */                                          /*i < CO*/                                                        /*LS * 2; i++) putch*/
